-- V2__create_schools.sql
-- create the schools table. Every column here must line up with the School entity + inherited BaseEntity,
-- because spring.jpa.hibernate.ddl-auto=validate makes Hibernate check the entity against the real table at
-- startup and fail on any mismatch
CREATE TABLE schools (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    short_name      VARCHAR(50)     NOT NULL,
    email_domain    VARCHAR(255)    NOT NULL UNIQUE,
    city            VARCHAR(100),
    active          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL
);