-- V4__create_users_table.sql
-- Create the users table. Columns must line up with the User entity + BaseEntity
-- (ddl-auto=validate checks them at startup). Users are created via registration,
-- so there is NO seed migration for this table.
CREATE TABLE users (
    id                  BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255)        NOT NULL UNIQUE,
    password_hash       VARCHAR(255)        NOT NULL,
    display_name        VARCHAR(100)        NOT NULL,
    school_id           BIGINT              NOT NULL REFERENCES schools(id),
    role                VARCHAR(20)         NOT NULL,
    email_verified      BOOLEAN             NOT NULL DEFAULT FALSE,
    reputation_score    INTEGER             NOT NULL DEFAULT 0,
    created_at          TIMESTAMP           NOT NULL,
    updated_at          TIMESTAMP           NOT NULL
);

CREATE INDEX id_users_school_id ON users(school_id);