-- A user can have one active verification code at a time
CREATE TABLE email_verification_codes (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    code_hash       VARCHAR(64)     NOT NULL,
    expires_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP       NOT NULL
);