-- Reference data for classifying marketplace listings
-- Hibernate validates this schema against Category on application startup
CREATE TABLE categories (
    id          BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)        NOT NULL,
    slug        VARCHAR(100)        NOT NULL UNIQUE,
    active      BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP           NOT NULL,
    updated_at  TIMESTAMP           NOT NULL
);