-- Marketplace listings
-- Item owner and school are server-derived in 3.4, this migration only defines storage
CREATE TABLE items (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Foreign key: an item belongs to one owner, school snapshot and category
    owner_id        BIGINT              NOT NULL REFERENCES users(id),
    school_id       BIGINT              NOT NULL REFERENCES schools(id),
    category_id     BIGINT              NOT NULL REFERENCES categories(id),

    title           VARCHAR(150)        NOT NULL,
    description     TEXT                NOT NULL,
    condition       VARCHAR(50)         NOT NULL,

    exchange_type   VARCHAR(20)         NOT NULL,
    price_amount    NUMERIC(10, 2),
    status          VARCHAR(20)         NOT NULL DEFAULT 'DRAFT',
    location_hint   VARCHAR(255),

    -- Used later to prevent two trade requests reserving the same Item
    version         BIGINT              NOT NULL DEFAULT 0,

    created_at      TIMESTAMP           NOT NULL,
    updated_at      TIMESTAMP           NOT NULL,

    CONSTRAINT chk_items_exchange_type
            CHECK (exchange_type IN ('FREE', 'SWAP', 'SELL')),

    CONSTRAINT chk_items_status
            CHECK (status IN (
                'DRAFT', 'AVAILABLE', 'RESERVED', 'COMPLETED', 'ARCHIVED', 'UNDER_REVIEW'
            )),

    -- Money rule: only SELL has a positive EUR price
    CONSTRAINT chk_items_price_amount
            CHECK (
                (exchange_type = 'SELL' AND price_amount IS NOT NULL AND price_amount > 0)
                OR
                (exchange_type IN ('FREE', 'SWAP') AND price_amount IS NULL)
            )
);

CREATE INDEX idx_items_owner_id ON items(owner_id);
CREATE INDEX idx_items_school_id ON items(school_id);
CREATE INDEX idx_items_category_id ON items(category_id);
CREATE INDEX idx_items_status ON items(status);