-- Image metadata only. The actual file is managed by StorageService
CREATE TABLE item_images (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT              NOT NULL REFERENCES items(id),
    storage_key     VARCHAR(1024)       NOT NULL,
    sort_order      INTEGER             NOT NULL,
    created_at      TIMESTAMP           NOT NULL,
    updated_at      TIMESTAMP           NOT NULL,

    -- A storage object belongs to exactly one image row
    CONSTRAINT uq_item_images_storage_key
            UNIQUE (storage_key),

    -- 0 is the cover image; each item has one image at each display position
    CONSTRAINT uq_item_images_item_sort_order
            UNIQUE (item_id, sort_order),

    CONSTRAINT chk_item_images_sort_order
            CHECK (sort_order >= 0)
);