spring.application.name=unitrovee

# --- Datasource ---
spring.datasource.url=jdbc:postgresql://localhost:5432/unitrovee
spring.datasource.username=unitrovee
spring.datasource.password=${POSTGRES_PASSWORD}